// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClnmJ4exx5SWXFBk6W0t7rzZ-6i_tG8nQ',
    appId: '1:78057156565:web:a0537399ebedf475c0d75c',
    messagingSenderId: '78057156565',
    projectId: 'chatflutter-24055',
    authDomain: 'chatflutter-24055.firebaseapp.com',
    storageBucket: 'chatflutter-24055.appspot.com',
    measurementId: 'G-4C37CNB70W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-nHIol-WZVx9qxn1d_KTpbKF3iFI8F0',
    appId: '1:78057156565:android:e32a4701dfad9563c0d75c',
    messagingSenderId: '78057156565',
    projectId: 'chatflutter-24055',
    storageBucket: 'chatflutter-24055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA4zL_TkYSTU5uVW302BDbHJasSZTaHZE',
    appId: '1:78057156565:ios:5cce8a1b27ae2bdac0d75c',
    messagingSenderId: '78057156565',
    projectId: 'chatflutter-24055',
    storageBucket: 'chatflutter-24055.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
